name: build-push-harbor
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
on:
  push:
    branches:
      - '**'
permissions:
  scm-token-own: read
  scm-token-org: read

jobs:
 docker-build-push-harbor:
    steps:
      
    - id: git-credentials
      name: Setup git credentials
      uses: cloudbees-io/configure-git-global-credentials@v1

    - name: checkout-source-code
      uses: cloudbees-io/checkout@v1

    - id: build-go-binary
      name: Build Go binary
      uses: docker://golang:1.21
      run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags \"-static\"' -o configure-oci-credentials --buildvcs=0

    - id: dockerconfig
      name: Configure container registry credentials
      uses: cloudbees-io/configure-oci-credentials@v0
      with:
        registry: ${{ vars.STAGING_DOCKER_REGISTRY }}
        username: ${{ secrets.STAGING_DOCKER_USERNAME }}
        password: ${{ secrets.STAGING_DOCKER_PASSWORD }}

    - id: build-container
      name: Build container image
      uses: cloudbees-io/kaniko@v1
      kind: build
      with:
        context: ${{ cloudbees.workspace }}
        destination: registry.saas-dev.beescloud.com/staging/configure-oci-credentials:${{ cloudbees.scm.sha }}${{ cloudbees.scm.branch == 'main' && ',registry.saas-dev.beescloud.com/staging/configure-oci-credentials:v0.0.4' || '' }}
        
