apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: SelfTest

on:
  push:
    branches:
      - "*"

jobs:
  compat-check:
    #name: Check the action running on CBA
    steps:
      - uses: cloudbees-io/configure-oci-credentials@v0
        with:
          registry: ${{ vars.HARBOR_SERVER }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - uses: docker://alpine:3.18
        # We need something that uses ~/.docker/config.json but doesn't need a docker daemon
        # ideally we would just use ghcr.io/regclient/regctl:latest but that is a non-root user
        run: |
          apk add -U --no-cache curl ca-certificates
          curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >/usr/local/bin/regctl
          chmod 755 /usr/local/bin/regctl
          regctl image inspect ${{ vars.HARBOR_SERVER }}/staging/configure-oci-credentials:vmain
